name: 新規キャラクター提案
description: データベースに追加する新しいキャラクターを提案
title: "[キャラクター] "
labels: ["new-character"]
body:
  - type: markdown
    attributes:
      value: |
        新しいキャラクターを提案していただきありがとうございます！以下の情報を入力してください。
        これにより一貫したキャラクターファイルの作成に役立ちます。

  - type: input
    id: character_id
    attributes:
      label: キャラクターID
      description: |
        キャラクターの一意の識別子。
        小文字、数字、アンダースコアのみ使用可能（例：`john_smith`, `hero_01`）。
      placeholder: "your_character_id"
    validations:
      required: true

  - type: input
    id: character_name
    attributes:
      label: キャラクター名
      description: キャラクターのフルネーム
      placeholder: "田中 太郎"
    validations:
      required: true

  - type: input
    id: age
    attributes:
      label: 年齢
      description: キャラクターの年齢（数字または「不死」「不明」などの説明的な言葉）
      placeholder: "25"
    validations:
      required: true

  - type: dropdown
    id: role
    attributes:
      label: ストーリーでの役割
      description: 物語における主な役割
      options:
        - 主人公
        - 敵役
        - 脇役
        - 端役
        - その他
    validations:
      required: true

  - type: textarea
    id: personality
    attributes:
      label: 性格
      description: 主な性格特性と特徴
      placeholder: |
        - 勇敢で決断力がある
        - 怒りやすいが忠実
        - ドライなユーモアがある
    validations:
      required: true

  - type: textarea
    id: speech_style
    attributes:
      label: 話し方 / 声
      description: このキャラクターはどのように話しますか？方言、丁寧さのレベル、決め台詞などを含めてください。
      placeholder: |
        時折古風なフレーズを交えたフォーマルな話し方。
        よく「なるほど」「承知しました」と言う。
    validations:
      required: true

  - type: textarea
    id: background
    attributes:
      label: 背景
      description: 簡潔な経歴と歴史
      placeholder: |
        小さな村で生まれ、12歳から騎士として訓練を受けた...
    validations:
      required: true

  - type: textarea
    id: goals
    attributes:
      label: 目標と動機
      description: このキャラクターを動かすものは何ですか？何を達成しようとしていますか？
      placeholder: |
        主な目標: 故郷を守る
        動機: 過去の失敗への罪悪感
    validations:
      required: true

  - type: textarea
    id: secrets
    attributes:
      label: 秘密（オプション）
      description: このキャラクターが隠している秘密（適切な場合を除き、AIによって明かされません）
      placeholder: |
        - 密かに王の動機を疑っている
        - 禁じられた恋がある

  - type: textarea
    id: relationships
    attributes:
      label: 関係性
      description: |
        他のキャラクターとの主な関係。
        既存のキャラクターの場合は、キャラクターIDを使用してください。
      placeholder: |
        - alice_wonder: 友人（幼なじみ）
        - dark_lord: 敵（宿敵）

  - type: textarea
    id: tags
    attributes:
      label: 推奨タグ
      description: |
        prefix/value 形式のタグ。有効なプレフィックス: role, trait, species, origin, faction, status, archetype, power, era, genre
      placeholder: |
        - role/protagonist
        - trait/brave
        - species/human
        - archetype/hero
    validations:
      required: true

  - type: textarea
    id: ai_boundaries
    attributes:
      label: AI演技の境界
      description: このキャラクターを演じる際にAIが避けるべきことは何ですか？
      placeholder: |
        - キャラクターを破らない
        - 秘密のアイデンティティを明かさない
        - 過激な暴力を避ける

  - type: checkboxes
    id: checklist
    attributes:
      label: 提出前チェックリスト
      description: 以下を確認してください
      options:
        - label: キャラクターIDが命名規則に従っている（小文字、数字、アンダースコアのみ）
          required: true
        - label: タグが vocab.yml の有効なプレフィックスを使用している
          required: true
        - label: 関係性が既存のキャラクターIDを参照している（または一緒に追加される）
          required: true
        - label: キャラクターテンプレート (_TEMPLATE.character.yml) を確認した
          required: true
